export default `_Content note: This post refers to data on internet shutdown instances collated by trusted partners in Russia. To date, we have not yet verified these numbers using Access Now’s_ [**_Shutdown Tracker Optimization Project (STOP) methodology_**](https://www.accessnow.org/guide/shutdown-tracker-optimization-project/)_. As such, the data contained in this post may not correspond to future verified figures. You can find more information about how we track and measure global internet shutdowns_ [**_here_**](https://www.accessnow.org/guide/shutdown-tracker-optimization-project/#faq)_._ 

* * *

Russia has recently been breaking its own [**records when it comes to cutting connectivity**](https://globalvoices.org/2025/01/22/shutting-down-the-net-the-growing-threat-of-russian-internet-censorship/) across the country. According to Russian internet monitoring project **[Na Svyazi](https://t.me/na_svyazi_helpdesk)**, authorities shut down the internet more [**than 650 times**](https://meduza.io/news/2025/07/01/na-svyazi-v-rossii-v-iyune-655-raz-otklyuchali-mobilnyy-internet) in June alone, [**most frequently**](https://meduza.io/en/feature/2025/07/07/mapping-russia-s-internet-blackouts) in the cities of Nizhny Novgorod, Saratov, Tula, Omsk, and Rostov. Meanwhile in Moscow, internet shutdowns intensified during May’s [**Victory Day celebration**](https://www.accessnow.org/press-release/kremlin-must-end-internet-shutdowns-national-events/), with media outlet [**_Meduza_ reporting**](https://meduza.io/en/feature/2025/07/07/mapping-russia-s-internet-blackouts) that the internet [**was jammed 17 times**](https://meduza.io/en/feature/2025/07/07/mapping-russia-s-internet-blackouts) in the past two months. And now Russian authorities look set to tighten their iron grip over the internet even further, by potentially blocking WhatsApp across the country in a bid to push people onto highly surveilled, government-controlled messaging services instead.  

##### The daily impact of internet shutdowns

These shutdowns drastically affect the day-to-day lives of everyone in Russia. People [**struggle**](https://novayagazeta.ru/articles/2025/06/19/stranu-otkliuchili) to make online or card payments, withdraw cash from certain ATMs, receive deliveries, access car sharing services, or use online navigation and map tools, among other things. In some cases, people must [**take a bus to the nearest town**](https://meduza.io/en/feature/2025/07/07/mapping-russia-s-internet-blackouts) with a functioning ATM, simply to withdraw cash to pay for groceries, while people whose work heavily depends on the internet risk [**losing their incomes**](https://meduza.io/feature/2025/07/01/vse-uzhe-shutyat-o-internet-dali-kak-goryachuyu-vodu).

Internet shutdowns also endanger people’s lives. According to independent media reports, [**shutdowns in the Udmurt Republic disabled an airstrike alarm**](https://novayagazeta.eu/articles/2025/07/08/gde-i-kak-v-rossii-otkliuchaiut-internet) at the Izhevsk Electromechanical Plant shortly before it was hit by a drone attack, resulting in the death of three people. Meanwhile, mobile internet disruptions mean that, in life-threatening situations, people have to waste precious time hunting for a signal to [**call for an ambulance**](https://meduza.io/en/feature/2025/07/07/mapping-russia-s-internet-blackouts) or doctor. 

##### **Justifying an online iron curtain**

Russian authorities frequently [**justify**](https://theins.ru/en/news/283119) cutting connectivity as necessary to combat drone attacks, such as those launched as part of the Ukrainian military’s June 2025 [****“**Spiderweb” operation**](https://meduza.io/en/feature/2025/06/03/the-impact-of-spiderweb). Yet an [**investigation by _The Insider_ and Na Svyazi**](https://theins.ru/en/news/282568) shows that fewer than half of all the shutdowns imposed since May 1 coincided with Ukraine’s drone attacks in the same regions, with disruptions recorded in many regions with no history of drone attacks or [**proximity to the frontlines**](https://meduza.io/en/feature/2025/07/07/mapping-russia-s-internet-blackouts), such as the Chukotka Autonomous Okrug.  

In an attempt to explain this discrepancy, some local authorities have [**claimed**](https://www.moscowtimes.ru/2025/06/17/v-kazhdom-tretem-regione-rossii-zaglushili-internet-a166310) that they are also forced to impose shutdowns due to law enforcement and telecommunications companies’  joint assessment of the “operational situation.” However, Russia’s track record on digital repression suggests that such authorities may be using both drone attacks and vague “operational” concerns as a pretext to restrict people in Russia from accessing information online or exercising their right to freedom of speech, especially via messaging apps. On [**June 30 alone, for example**](https://www.agents.media/v-odnovremennyh-sboyah-v-whatsapp-i-telegram-uvideli-podgotovku-k-blokirovke-servisov/), more than 12,000 reports of Telegram disruptions and nearly 1,500 reports of disruptions to WhatsApp were [**submitted**](https://www.agents.media/v-odnovremennyh-sboyah-v-whatsapp-i-telegram-uvideli-podgotovku-k-blokirovke-servisov/) to both Na Svyazi and connectivity monitoring service [**Downdetector**](https://downdetector.com/). Subsequently, on July 4, Telegram and WhatsApp [**were again throttled in Moscow**](https://t.me/zatelecom/30661) and elsewhere.

Internet freedom advocates in Russia [**suggest**](https://www.dw.com/ru/drony-but-po-ekonomike-rf-daze-bez-vzryvov/a-73229974) that local officials may be cutting off mobile internet in an attempt to convince the Kremlin that they are taking measures against drones, despite the fact that mobile internet [**is not strictly needed**](https://visitukraine.today/blog/6346/communications-under-threat-will-ukraine-start-jamming-mobile-internet-due-to-drone-attacks#are-there-plans-to-shut-down-communications-what-the-government-is-saying) to operate drones. This weaponization and normalization of internet shutdowns reflect a wider trend, with [**conflict now the leading trigger for shutdowns worldwide**](https://www.accessnow.org/internet-shutdowns-2024/).

##### What happens next?

The Russian government continues to systematically isolate the country’s internet infrastructure and, therefore, the people of Russia from the rest of the world. In June 2025, Cloudflare [**confirmed**](https://blog.cloudflare.com/russian-internet-users-are-unable-to-access-the-open-internet/) that Russian authorities are preventing people in Russia from accessing websites and services that rely on its platform, by limiting the amount of content that can be served to a mere 16 KB, rendering many websites barely usable. This goes hand-in-hand with the ongoing [**throttling of YouTube**](https://meduza.io/en/news/2024/12/23/youtube-traffic-in-russia-drops-to-20-percent-of-pre-throttling-levels-platform-de-factoblocked-in-country), the [**deplatforming of VPNs**](https://www.techradar.com/vpn/vpn-privacy-security/a-new-wave-of-blocks-in-russia-targets-vpn-apps-and-cloudflare-subnets) from Apple’s App Store, and [**bans on Facebook and Instagram**](https://www.theguardian.com/world/2022/mar/21/russia-bans-facebook-and-instagram-under-extremism-law) — all measures instituted in an effort to prevent people from accessing independent information and resisting President Vladimir Putin’s propaganda. 

Now it seems that WhatsApp, one of the last remaining channels allowing for the free exchange of opinions, may be in danger. It has been suggested that the [**government plans**](https://meduza.io/en/feature/2025/07/18/there-s-a-99-percent-chance-it-will-happen) to block this app in a bid to [**push people to switch to an alternative messenger app known as Max**](https://www.rferl.org/a/russia-sovereign-internet-super-app-tech/33439093.html), which will be [**pre-installed on all smartphones sold in Russia**](https://cybernews.com/news/russia-to-create-state-run-messaging-app-whatsapp-telegram/), integrated with government services, and heavily controlled and surveilled by authorities. We’ve seen this playbook before, when Russian authorities [**designated**](https://www.bbc.com/news/technology-63218095) Meta as an extremist organization and [**throttled YouTube**](https://meduza.io/en/news/2024/12/23/youtube-traffic-in-russia-drops-to-20-percent-of-pre-throttling-levels-platform-de-factoblocked-in-country), then [**encouraged people**](https://rus.azattyq.org/a/31750439.html) to switch to Russian platforms like VK, Odnoklassniki, and [**RuTube**](https://www.codastory.com/newsletters/russia-rutube/).

With [**digital authoritarianism**](https://www.accessnow.org/digital-dictatorship-and-resistance-in-eastern-europe-and-central-asia/) only deepening in Russia, it is vital to break this increasing and ever-more disturbing pattern of cutting connectivity. Russian authorities must stop hampering people’s access to an open, free, and secure internet, by ceasing all throttling measures and refraining from imposing any further internet shutdowns. At the same time, internet service providers should resist any orders that would stop them from providing high-quality, unrestricted internet access — a prerequisite for allowing the people of Russia to exercise their human rights to freedom of expression and information.`;
