name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

# Cancel in-progress runs when a new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      cache-hit: ${{ steps.cache-deps.outputs.cache-hit }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js using mise
        uses: jdx/mise-action@v2
        with:
          cache: true

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.local/share/pnpm/store
            node_modules
          key: ${{ runner.os }}-deps-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile

  lint:
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js using mise
        uses: jdx/mise-action@v2
        with:
          cache: true

      - name: Restore dependencies
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.local/share/pnpm/store
            node_modules
          key: ${{ runner.os }}-deps-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies if cache failed
        run: |
          if [ ! -d "node_modules" ]; then
            echo "Cache restore failed, installing dependencies..."
            pnpm install --frozen-lockfile
          fi

      - name: Lint
        run: pnpm lint

  test:
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js using mise
        uses: jdx/mise-action@v2
        with:
          cache: true

      - name: Restore dependencies
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.local/share/pnpm/store
            node_modules
          key: ${{ runner.os }}-deps-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies if cache failed
        run: |
          if [ ! -d "node_modules" ]; then
            echo "Cache restore failed, installing dependencies..."
            pnpm install --frozen-lockfile
          fi

      - name: Test
        run: pnpm test

  build:
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js using mise
        uses: jdx/mise-action@v2
        with:
          cache: true

      - name: Restore dependencies
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.local/share/pnpm/store
            node_modules
          key: ${{ runner.os }}-deps-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies if cache failed
        run: |
          if [ ! -d "node_modules" ]; then
            echo "Cache restore failed, installing dependencies..."
            pnpm install --frozen-lockfile
          fi

      - name: Build
        run: pnpm build

      - name: Test CLI
        run: pnpm cli --help
